-- Flying Cobra · 0005 animal seed
-- The whole roster plus the rules that place each animal in a bag (docs/ALGORITHMS.md §3, §6–§9).
-- Idempotent: animals upsert on slug; seed rules are wiped (note like 'seed:%') and re-inserted.
-- animal_counters are created by the animals_counter trigger — never insert them here.
--
-- Palettes are per FAMILY so same-family cards look related:
--   swift amber/sand · steady forest green · calm dusk lavender · gentle terracotta
--   time indigo night (night bag) / dawn peach (dawn bag) · explorer ochre · regional teal
--   weekly deep crimson · migratory sky blue · secret iridescent purple · national saffron

-- ---------- animals ----------
with pal(family, bag, palette) as (values
  ('swift',     'default', '{"bg":"#F4A940","fg":"#3B2208","accent":"#FFE3A8"}'::jsonb),
  ('steady',    'default', '{"bg":"#2F6B3A","fg":"#EAF5E6","accent":"#9BD47F"}'::jsonb),
  ('calm',      'default', '{"bg":"#6E5B9A","fg":"#F6F1FF","accent":"#D6C6F2"}'::jsonb),
  ('gentle',    'default', '{"bg":"#B35A3C","fg":"#FFF1E8","accent":"#F2B48F"}'::jsonb),
  ('time',      'night',   '{"bg":"#1F2459","fg":"#E8E9FF","accent":"#F9C9A8"}'::jsonb),
  ('time',      'dawn',    '{"bg":"#F7C9A6","fg":"#2A2F6B","accent":"#1F2459"}'::jsonb),
  ('explorer',  'default', '{"bg":"#C9962B","fg":"#2E2208","accent":"#F5E2A8"}'::jsonb),
  ('regional',  'default', '{"bg":"#1F7A78","fg":"#E6FAF8","accent":"#8FDBD6"}'::jsonb),
  ('weekly',    'default', '{"bg":"#7A1430","fg":"#FFE9EE","accent":"#F2A3B5"}'::jsonb),
  ('migratory', 'default', '{"bg":"#4FA3E0","fg":"#0F2A44","accent":"#DDF0FF"}'::jsonb),
  ('secret',    'default', '{"bg":"#5B2A8C","fg":"#F7ECFF","accent":"#C77DFF"}'::jsonb),
  ('national',  'default', '{"bg":"#FF9933","fg":"#3B1F00","accent":"#FFE0B3"}'::jsonb)
),
a(slug, code, name, family, bag, rarity, flavour_line, encyclopedia, is_secret, sort_order) as (values

-- ===== swift (speed band P ≥ 0.60) =====
('chinkara','CHK','Chinkara','swift','default','common','the desert dancer',
 '{"facts":["Can go for long stretches without drinking, drawing moisture from dew and the plants it eats","Both sexes carry ringed horns; a male''s can reach 25–30 cm","Protected for centuries by the Bishnoi communities of Rajasthan, who treat the gazelle as kin"],"habitat":"arid plains, thorn scrub and dunes","size":"about 65 cm at the shoulder, around 23 kg","superpower":"lightness that turns sand into a running track","india_note":"the Indian gazelle of the Thar — Rajasthan, Gujarat, Madhya Pradesh and the Deccan drylands"}',
 false, 10),
('horse','HRS','Horse','swift','default','common','born to gallop',
 '{"facts":["Horses were first domesticated on the Eurasian steppe roughly 5,500 years ago","A horse can doze standing up thanks to a locking system of tendons and ligaments called the stay apparatus","Racing Quarter Horses have been clocked at over 70 km/h in short sprints"],"habitat":"open grasslands, now almost every landscape alongside people","size":"1.4–1.8 m at the withers, 400–600 kg","superpower":"a stride built for the long open road","india_note":"the Marwari of Rajasthan, with its inward-curving ears, and the Kathiawari of Gujarat are India''s own breeds"}',
 false, 11),
('blackbuck','BBK','Blackbuck','swift','default','uncommon','the spiral-horned sprinter',
 '{"facts":["One of the fastest antelopes alive, with sprints of around 80 km/h","Males carry spiralled horns of up to 60–75 cm with three or four twists","Males darken to near-black with age while females stay fawn-coloured"],"habitat":"open grassland and semi-desert","size":"74–84 cm at the shoulder, 20–57 kg","superpower":"explosive speed across open ground","india_note":"state animal of Andhra Pradesh, Haryana and Punjab; big herds at Velavadar (Gujarat) and Tal Chhapar (Rajasthan)"}',
 false, 12),
('indian-hare','HARE','Indian Hare','swift','default','uncommon','quick as a thought',
 '{"facts":["Named the black-naped hare for the dark patch on the back of its neck","Does not dig burrows — it rests in a shallow scrape in the grass called a form","Leverets are born fully furred with their eyes open and can move within hours"],"habitat":"scrub, grassland, farmland edges","size":"40–70 cm long, 2–3 kg","superpower":"zigzag acceleration that leaves pursuers guessing","india_note":"found across the subcontinent from the plains to the lower Himalaya"}',
 false, 13),
('peregrine-falcon','PRG','Peregrine Falcon','swift','default','rare','the fastest thing alive',
 '{"facts":["The fastest animal on Earth: hunting dives (stoops) exceed 300 km/h","A bony baffle inside each nostril lets it breathe while diving at extreme speed","Breeds on every continent except Antarctica, from sea cliffs to city skyscrapers"],"habitat":"cliffs, wetlands, coasts and cities","size":"34–58 cm long, wingspan 74–120 cm; females larger","superpower":"a dive faster than any other living thing","india_note":"the resident Shaheen falcon breeds on Indian cliffs, joined every winter by migrants from Siberia"}',
 false, 14),
('cheetah','CHT','Cheetah','swift','default','epic','the comeback sprinter',
 '{"facts":["Accelerates from 0 to 100 km/h in about three seconds and sprints at over 100 km/h","Declared extinct in India in 1952, then reintroduced to Kuno National Park, Madhya Pradesh in September 2022 with eight cheetahs from Namibia, followed by twelve from South Africa in 2023","Semi-retractable claws grip like running spikes while the long tail steers through turns"],"habitat":"open savanna and grassland","size":"67–94 cm at the shoulder, 21–72 kg","superpower":"the fastest land sprint on the planet","india_note":"the name comes from the Sanskrit chitraka, the spotted one; India''s new population lives at Kuno"}',
 false, 15),

-- ===== steady (0.47 ≤ P < 0.60) =====
('chital','CHTL','Chital','steady','default','common','the dappled wanderer',
 '{"facts":["Keeps its white spots for life, unlike most deer which lose them after fawnhood","Often grazes beneath langur troops, eating dropped fruit and listening for their alarm calls","Stags shed and regrow three-tined antlers every year"],"habitat":"deciduous forest and grassland edges","size":"about 90 cm at the shoulder, 30–75 kg","superpower":"an easy rhythm that carries the whole herd","india_note":"the most abundant deer in India, from Corbett to Bandipur"}',
 false, 20),
('desi-dog','DOG','Desi Dog','steady','default','common','everyone''s running partner',
 '{"facts":["Dog remains and figurines from Harappan sites show dogs of this type living with people more than 4,500 years ago","Shaped by natural selection rather than breeders: wedge head, erect ears, curled tail, short coat","Known for robust immunity and sharp territorial instinct, which is why villages trust it as a watchdog"],"habitat":"villages, towns and city streets","size":"46–64 cm at the shoulder, 15–30 kg","superpower":"loyal stamina that matches any pace","india_note":"the Indian pariah dog, a native landrace found in every corner of the subcontinent"}',
 false, 21),
('nilgai','NLG','Nilgai','steady','default','uncommon','the blue bull of the plains',
 '{"facts":["The largest antelope in Asia — bulls can top 250 kg","Only adult males turn the blue-grey that gives the animal its name; females and young stay tawny","Herds return to the same communal dung piles, a rare habit among antelopes"],"habitat":"open scrub, farmland and dry forest","size":"1.2–1.5 m at the shoulder, 100–290 kg","superpower":"a powerful, ground-eating trot","india_note":"common across the northern plains; its cow-like name has long earned it protection"}',
 false, 22),
('dhole','DHL','Dhole','steady','default','uncommon','the pack hunter',
 '{"facts":["Hunts in packs of five to twelve and coordinates with whistles rather than howls","Can bring down prey such as sambar that weigh ten times as much as a single dhole","Pups eat first at a kill, and the pack regurgitates food for them"],"habitat":"deciduous and evergreen forest","size":"about 90 cm long, 12–20 kg","superpower":"teamwork that never breaks stride","india_note":"the Asiatic wild dog; strongholds in the Western Ghats, central India and the northeast"}',
 false, 23),
('indian-wolf','WLF','Indian Wolf','steady','default','rare','the grassland ghost',
 '{"facts":["Genomic studies place it among the oldest living wolf lineages","Smaller and thinner-coated than northern grey wolves, built for heat rather than snow","Lives in open grassland and scrub, hunting hare, rodents and blackbuck in small packs"],"habitat":"grassland, scrub and semi-arid plains","size":"60–70 cm at the shoulder, 20–30 kg","superpower":"a trot that can go on for hours","india_note":"only a few thousand remain, in places like Nannaj, Kutch and the Deccan grasslands"}',
 false, 24),
('leopard','LPD','Leopard','steady','default','epic','the shadow that walks anywhere',
 '{"facts":["Hauls kills heavier than itself up into trees to keep them from hyenas and tigers","The most adaptable big cat — leopards live inside Mumbai''s Sanjay Gandhi National Park","The 2022 national estimate counted around 13,800 leopards in India"],"habitat":"forest, scrub, rocky hills and city edges","size":"45–80 cm at the shoulder, 30–70 kg","superpower":"silent strength that fits any landscape","india_note":"found from the Himalayan foothills to the Western Ghats; the black panther is a dark-coated leopard"}',
 false, 25),

-- ===== calm (0.35 ≤ P < 0.47) =====
('rabbit','RBT','Rabbit','calm','default','common','soft paws, big heart',
 '{"facts":["Eyes set high on the head give almost 360-degree vision, with a small blind spot right in front of the nose","Its teeth never stop growing and are worn down by constant grazing","A happy rabbit performs a twisting mid-air leap called a binky"],"habitat":"meadows and warrens; homes and gardens as a pet","size":"35–50 cm long, 1–2.5 kg","superpower":"gentle energy and a quick happy hop","india_note":"the domestic rabbit is a well-loved pet across India; the native wild cousin is the Indian hare"}',
 false, 30),
('cat','CAT','Cat','calm','default','common','curious and unbothered',
 '{"facts":["Domesticated from the African wildcat in the Near East around 10,000 years ago","Each ear has about 32 muscles and can swivel roughly 180 degrees","A cat''s purr vibrates at roughly 25–150 Hz"],"habitat":"wherever people live","size":"23–25 cm at the shoulder, 3.5–5 kg","superpower":"calm focus and perfect balance","india_note":"at home in every Indian town; its wild relative, the Asiatic wildcat, roams the Thar"}',
 false, 31),
('grey-langur','LNG','Grey Langur','calm','default','uncommon','the temple acrobat',
 '{"facts":["A multi-chambered stomach ferments leaves that other monkeys cannot digest","Its booming alarm calls warn chital and other animals when a predator is near","Troops can number dozens of animals and spend much of the day on the ground"],"habitat":"forest, farmland, villages and temple towns","size":"40–78 cm body, tail up to 1 m, 11–18 kg","superpower":"graceful leaps and watchful patience","india_note":"the Hanuman langur, revered across India and common from Rajasthan to the Western Ghats"}',
 false, 32),
('peacock','PCK','Peacock','calm','default','uncommon','the monsoon dancer',
 '{"facts":["National bird of India since 1963","The train is not a tail but about 150–200 elongated upper tail covert feathers, shed and regrown every year","Peafowl fly short distances and roost high in trees at night"],"habitat":"open forest, farmland and village edges","size":"males 180–230 cm including the train, 4–6 kg","superpower":"a display that stops everyone in their tracks","india_note":"found wild across the country; its calls announce the first rains"}',
 false, 33),
('smooth-coated-otter','OTR','Smooth-coated Otter','calm','default','rare','the river''s playmate',
 '{"facts":["The largest otter in South Asia at 7–11 kg","Lives in family groups that herd fish together into the shallows","Fishing families in parts of Bengal have trained these otters for generations to drive fish into nets"],"habitat":"rivers, wetlands, mangroves and reservoirs","size":"1–1.3 m including the tail, 7–11 kg","superpower":"playful teamwork in the water","india_note":"seen on the Chambal, Cauvery and Periyar; listed as Vulnerable"}',
 false, 34),
('mouse-deer','MSD','Mouse Deer','calm','default','epic','small, secret, sure-footed',
 '{"facts":["One of the smallest hoofed mammals on Earth, weighing just 2–3 kg","Has no antlers; males grow tusk-like upper canines instead","Dives into water and hides submerged when threatened"],"habitat":"moist deciduous and evergreen forest undergrowth","size":"50–58 cm long, 25–35 cm tall, 2–3 kg","superpower":"stillness that makes it almost invisible","india_note":"the Indian spotted chevrotain; captive-bred animals have been released into Amrabad Tiger Reserve, Telangana"}',
 false, 35),

-- ===== gentle (P < 0.35) =====
('star-tortoise','TRT','Star Tortoise','gentle','default','common','unstoppable',
 '{"facts":["Lives 35–80 years","The star pattern on its high-domed shell breaks up its outline in dry grass","The dome is so round that a flipped tortoise can roll itself upright"],"habitat":"dry scrub, grassland and thorn forest","size":"15–25 cm shell, females up to 38 cm, 1.3–2.2 kg","superpower":"patience that outlasts everything","india_note":"native to Gujarat, Rajasthan, Tamil Nadu, Andhra Pradesh and Karnataka; protected under CITES Appendix I since 2019"}',
 false, 40),
('hamster','HMS','Hamster','gentle','default','common','the midnight marathoner',
 '{"facts":["Cheek pouches stretch back to the shoulders and can carry a huge haul of seeds","On a running wheel, a hamster can clock several kilometres in a single night","Almost every pet golden hamster descends from one mother and her litter collected near Aleppo in 1930"],"habitat":"dry steppe burrows; homes as a pet","size":"13–18 cm long, 100–150 g","superpower":"tiny legs, enormous nightly mileage","india_note":"not native to India, but a favourite first pet in Indian homes"}',
 false, 41),
('sloth-bear','SLB','Sloth Bear','gentle','default','uncommon','the shaggy wanderer',
 '{"facts":["Closes its nostrils and sucks termites through a gap left by missing upper front teeth, loud enough to hear far across the forest","The only bear that routinely carries its cubs on its back","Baloo in Kipling''s Jungle Book is a sloth bear"],"habitat":"dry and moist forest, rocky scrub","size":"60–90 cm at the shoulder, 55–145 kg","superpower":"a steady shamble that covers the whole forest by night","india_note":"found across peninsular India; Daroji Sloth Bear Sanctuary in Karnataka protects a famous population"}',
 false, 42),
('porcupine','PRC','Porcupine','gentle','default','uncommon','the quilled knight',
 '{"facts":["The largest rodent in India at 11–18 kg","Quills are modified hairs; the hollow ones on the tail rattle as a warning","Gnaws on bones and shed antlers to get calcium for its quills"],"habitat":"rocky hills, scrub and forest; digs deep burrows","size":"70–90 cm long, 11–18 kg","superpower":"armour that asks nothing to prove itself","india_note":"the Indian crested porcupine lives across the country except the high Himalaya"}',
 false, 43),
('pangolin','PNG','Pangolin','gentle','default','rare','the armoured pilgrim',
 '{"facts":["The only mammal covered in overlapping keratin scales","Rolls into a tight ball that even big cats struggle to open","Has no teeth; a long sticky tongue rooted deep in the chest flicks into ant and termite nests"],"habitat":"forest, grassland and farmland with termite mounds","size":"84–122 cm including the tail, 10–16 kg","superpower":"quiet resilience under a coat of armour","india_note":"the Indian pangolin is Endangered and the most trafficked mammal group in the world"}',
 false, 44),
('elephant','ELE','Elephant','gentle','default','epic','the tireless traveller',
 '{"facts":["Wild elephants can walk 30–50 km in a day while feeding","Eats up to 150 kg of vegetation a day over about 18 hours of foraging","Communicates with infrasound below human hearing that travels for kilometres"],"habitat":"forest, grassland and river valleys","size":"2.5–3 m at the shoulder, 3,000–5,000 kg","superpower":"distance that never seems to tire","india_note":"India holds about 60 percent of all wild Asian elephants, around 27,000 in the 2017 census; National Heritage Animal since 2010"}',
 false, 45),

-- ===== time · night bag =====
('indian-eagle-owl','OWL','Indian Eagle-Owl','time','night','common','the keeper of the dark',
 '{"facts":["Its deep two-note call carries across ravines at dusk","Comb-like edges on the flight feathers let it fly almost silently","Nests on bare cliff ledges and rocky slopes rather than in trees"],"habitat":"rocky hills, ravines and scrub","size":"50–60 cm long, wingspan around 1.25–1.5 m","superpower":"sight and silence in total darkness","india_note":"found only in the Indian subcontinent, from the Himalayan foothills to the southern hills"}',
 false, 50),
('nightjar','NJR','Indian Nightjar','time','night','uncommon','the voice of the night road',
 '{"facts":["Its call sounds like a ping-pong ball bouncing to a stop","Lays its eggs directly on bare ground with no nest at all","By day it sits motionless among dead leaves and is almost impossible to spot"],"habitat":"open scrub, dry forest and roadsides","size":"about 24 cm long","superpower":"hiding in plain sight until the light goes","india_note":"common across India; its eyes glow in headlights on country roads at night"}',
 false, 51),
('fruit-bat','BAT','Indian Flying Fox','time','night','uncommon','the orchard''s night gardener',
 '{"facts":["One of the largest bats in the world, with a wingspan of up to 1.5 m","Finds food by sight and smell rather than echolocation","Colonies roost in the same big banyan or tamarind trees for decades"],"habitat":"large roost trees near orchards, rivers and towns","size":"20–28 cm body, 0.6–1.6 kg","superpower":"pollinating and planting forests by night","india_note":"found across India; a key seed disperser for figs, mahua and many wild fruit trees"}',
 false, 52),
('palm-civet','CVT','Palm Civet','time','night','rare','the rooftop wanderer',
 '{"facts":["Nicknamed the toddy cat for its taste for palm sap collected in toddy pots","Loves ripe fruit, including coffee cherries, and spreads the seeds it swallows","Lives happily in attics and roof spaces, patrolling rooftops after dark"],"habitat":"forest, plantations and towns","size":"43–71 cm body, tail 40–66 cm, 2–5 kg","superpower":"a rooftop route no one else knows","india_note":"the Asian palm civet lives alongside people in almost every Indian city"}',
 false, 53),

-- ===== time · dawn bag =====
('rooster','RST','Rooster','time','dawn','common','the one who wakes the sun',
 '{"facts":["Every domestic chicken descends from the red junglefowl of South and Southeast Asia","Roosters begin crowing before first light using an internal circadian clock, not the sunrise itself","Chickens can see ultraviolet light that humans cannot"],"habitat":"farms, villages and backyards","size":"2–4 kg; Aseel cocks heavier","superpower":"a wake-up call that beats the sun","india_note":"India''s Aseel and the black-feathered Kadaknath of Madhya Pradesh are ancient native breeds"}',
 false, 54),
('bulbul','BLB','Red-vented Bulbul','time','dawn','common','the cheerful early bird',
 '{"facts":["Named for the crimson patch beneath its tail","Builds a neat cup nest low in bushes, often right beside houses","Listed among the world''s 100 worst invasive species where it has been introduced far from India"],"habitat":"gardens, scrub and open woodland","size":"about 20 cm long, 26–45 g","superpower":"the first cheerful note of the day","india_note":"one of the most familiar garden birds across the subcontinent"}',
 false, 55),
('koel','KOL','Asian Koel','time','dawn','uncommon','the singer of summer mornings',
 '{"facts":["Lays its eggs in the nests of crows, which raise the koel chick as their own","Males are glossy black with ruby-red eyes; females are brown and speckled","Unlike most cuckoos, the adults eat mostly fruit"],"habitat":"gardens, groves and city trees","size":"39–46 cm long","superpower":"a rising song that announces the hot season","india_note":"state bird of Jharkhand and Puducherry; its ku-oo call fills Indian mornings from March"}',
 false, 56),
('indian-roller','RLR','Indian Roller','time','dawn','rare','the sky''s own tumbler',
 '{"facts":["Named for its breeding display of rolling, tumbling dives through the air","Electric blue wing bands flash in flight but look dull when the bird is perched","Known as neelkanth, and sighting one on Dussehra is considered auspicious"],"habitat":"open country, farmland and roadside wires","size":"30–34 cm long","superpower":"a burst of blue that turns a morning into an event","india_note":"state bird of Odisha, Karnataka and Telangana"}',
 false, 57),

-- ===== explorer =====
('indian-fox','FOX','Indian Fox','explorer','default','common','the clever path-finder',
 '{"facts":["Found only in the Indian subcontinent","Digs dens with many entrances and escape tunnels","Eats everything from rodents and beetles to ber fruit and melons"],"habitat":"short grassland, scrub and farmland","size":"45–60 cm body, 2–4 kg","superpower":"knowing every path across open ground","india_note":"the Bengal fox, with its black-tipped tail, lives from the Thar to the Deccan"}',
 false, 60),
('bengal-monitor','MNT','Bengal Monitor','explorer','default','common','the wall-climber',
 '{"facts":["Grows up to about 1.75 m and climbs trees and walls with ease","Legend says the Maratha general Tanaji scaled Sinhagad fort with a rope tied to a monitor lizard","Flicks a forked tongue to taste scents in the air"],"habitat":"forest, scrub, farmland and old buildings","size":"up to 1.75 m long, up to 7 kg","superpower":"finding a way up anything","india_note":"called ghorpad in Marathi; found across most of India"}',
 false, 61),
('golden-jackal','JKL','Golden Jackal','explorer','default','uncommon','the storyteller''s trickster',
 '{"facts":["The cunning jackal of the Panchatantra tales","Mated pairs stay together for life, and grown pups often help raise the next litter","Its eerie evening chorus carries across fields and mangroves"],"habitat":"grassland, scrub, farmland and city edges","size":"70–85 cm body, 8–10 kg","superpower":"curiosity that explores every corner","india_note":"lives from the Himalayan foothills to Mumbai''s mangroves"}',
 false, 62),
('honey-badger','HBG','Honey Badger','explorer','default','rare','fearless, full stop',
 '{"facts":["Loose, thick skin lets it twist around and bite an attacker that has hold of it","Eats snakes, including cobras, and shrugs off venom that would fell larger animals","Named the most fearless animal in the world by Guinness World Records in 2002"],"habitat":"dry forest, scrub and grassland","size":"55–77 cm body, 9–16 kg","superpower":"the courage to try any route","india_note":"the ratel is found across India, from Gir to Ranthambore, but is rarely seen"}',
 false, 63),

-- ===== weekly =====
('red-panda','RPD','Red Panda','weekly','default','rare','the firefox of Sikkim',
 '{"facts":["An extended wrist bone works as a false thumb for gripping bamboo","Spends around 13 hours a day feeding on bamboo leaves","Wraps its bushy tail around itself as a blanket in the cold"],"habitat":"temperate Himalayan forest with bamboo","size":"50–64 cm body, tail 28–59 cm, 3–6 kg","superpower":"steady devotion to a daily routine","india_note":"state animal of Sikkim; found in Singalila and Khangchendzonga"}',
 false, 70),
('sambar','SMB','Sambar','weekly','default','rare','the forest''s alarm bell',
 '{"facts":["The largest deer in India, with stags up to 300 kg","Its loud belling alarm call is the sound trackers listen for when a tiger is moving","Wades into lakes to feed on water plants"],"habitat":"forest with water nearby","size":"1.2–1.6 m at the shoulder, 100–350 kg","superpower":"watchfulness the whole forest relies on","india_note":"common in Ranthambore, Kanha and the Western Ghats"}',
 false, 71),
('gharial','GHR','Gharial','weekly','default','rare','the river''s ancient fisher',
 '{"facts":["Its narrow snout carries about 110 interlocking teeth built for catching fish","Adult males grow a pot-shaped knob on the snout, the ghara that gives the species its name","The National Chambal Sanctuary shelters most of the world''s wild gharials"],"habitat":"deep, fast rivers with sandbanks","size":"3.5–4.5 m, up to 6 m; 150–250 kg","superpower":"a patience as old as the river","india_note":"Critically Endangered; found on the Chambal, Girwa and Gandak"}',
 false, 72),
('snow-leopard','SNL','Snow Leopard','weekly','default','epic','the grey ghost of the mountains',
 '{"facts":["Its tail is nearly as long as its body and doubles as a scarf in the cold","Can leap across gaps of up to 9 m or more","India''s 2024 assessment estimated around 718 snow leopards"],"habitat":"alpine slopes and cold deserts above 3,000 m","size":"55–65 cm at the shoulder, 22–55 kg","superpower":"calm mastery of the hardest terrain","india_note":"state animal of Ladakh and Himachal Pradesh; Hemis is known as the snow leopard capital"}',
 false, 73),
('black-panther','BPN','Black Panther','weekly','default','epic','the night within the forest',
 '{"facts":["Not a separate species but a leopard with melanism, a dark coat from a recessive gene","Rosettes are still visible in sunlight as ghost markings","Dark coats are more common in dense, humid forests"],"habitat":"dense moist forest","size":"45–80 cm at the shoulder, 30–70 kg","superpower":"perfect stealth in deep shade","india_note":"Kabini and Nagarhole in Karnataka are famous for sightings; Bagheera of the Jungle Book"}',
 false, 74),
('markhor','MKH','Markhor','weekly','default','epic','the corkscrew-horned king',
 '{"facts":["Males grow spiralling horns up to 1.6 m long","Stands on its hind legs to browse oak leaves high in the branches","The name means snake-eater in Persian, from old folklore"],"habitat":"steep rocky slopes and oak scrub, 600–3,600 m","size":"65–115 cm at the shoulder, 32–110 kg","superpower":"footing that laughs at cliffs","india_note":"in India found only in Jammu and Kashmir, in the Pir Panjal and Kazinag ranges"}',
 false, 75),
('bengal-tiger','TGR','Bengal Tiger','weekly','default','legendary','the striped king',
 '{"facts":["National animal of India; about three-quarters of the world''s wild tigers live here — roughly 3,680 in the 2022 census","Each tiger''s stripes are unique, and the pattern is on the skin as well as the fur","A strong swimmer that crosses wide rivers in the Sundarbans"],"habitat":"forest, grassland and mangroves","size":"90–110 cm at the shoulder, 180–260 kg for males","superpower":"presence that commands the whole forest","india_note":"Project Tiger launched in 1973 with nine reserves; India now has more than fifty"}',
 false, 76),
('great-indian-bustard','GIB','Great Indian Bustard','weekly','default','legendary','the giant of the grasslands',
 '{"facts":["Among the heaviest flying birds, with males up to 15 kg or more","Fewer than 200 remain, most in and around Desert National Park near Jaisalmer","Males inflate a throat pouch and boom during courtship"],"habitat":"arid grassland and scrub","size":"about 1–1.2 m tall, wingspan 2.1–2.5 m","superpower":"rare, magnificent and worth every step","india_note":"state bird of Rajasthan, the Godawan; a conservation breeding centre at Sam has hatched chicks since 2019"}',
 false, 77),

-- ===== migratory =====
('bar-headed-goose','BHG','Bar-headed Goose','migratory','default','rare','the one who crosses the Himalaya',
 '{"facts":["Migrates over the Himalaya at altitudes above 7,000 m","Its haemoglobin binds oxygen more tightly than that of other geese, letting it breathe thin air","Can climb from the plains to the high passes in a single night''s flight"],"habitat":"high-altitude lakes in summer, wetlands and fields in winter","size":"71–76 cm long, 2–3 kg","superpower":"crossing the highest mountains on Earth","india_note":"winters across India from Pong Dam to Chilika"}',
 false, 80),
('greater-flamingo','FLM','Greater Flamingo','migratory','default','rare','the pink pilgrim',
 '{"facts":["The largest flamingo, standing 110–150 cm","Its pink comes from carotenoids in the algae and shrimp it filters from the water","Flamingo City in the Great Rann of Kutch is India''s largest breeding colony"],"habitat":"salt pans, lagoons and mudflats","size":"110–150 cm tall, 2–4 kg","superpower":"journeys measured in thousands of birds","india_note":"state bird of Gujarat; vast flocks also winter in Mumbai''s Thane Creek"}',
 false, 81),
('amur-falcon','AMF','Amur Falcon','migratory','default','epic','the ocean-crossing voyager',
 '{"facts":["Makes one of the longest migrations of any raptor, about 22,000 km each year","Crosses the Arabian Sea non-stop, roughly 3,000 km over open water","Up to a million gather at Doyang reservoir in Nagaland each autumn"],"habitat":"open country; roosts in vast flocks on passage","size":"26–30 cm long, 100–190 g","superpower":"endurance across an entire ocean","india_note":"Nagaland villages around Pangti turned from hunting to protecting the falcons in 2013"}',
 false, 82),
('demoiselle-crane','DMC','Demoiselle Crane','migratory','default','epic','the kurjan of folk songs',
 '{"facts":["The smallest crane, yet it migrates over the Himalaya","Thousands gather every winter at Khichan in Rajasthan, where villagers have fed them for decades","Sung about as kurjan in Rajasthani folk songs"],"habitat":"steppe and grassland; fields and wetlands in winter","size":"85–100 cm tall, 2–3 kg","superpower":"grace that carries across continents","india_note":"winters in Rajasthan and Gujarat"}',
 false, 83),

-- ===== national (monthly fallback) =====
('ganges-river-dolphin','GRD','Ganges River Dolphin','national','default','epic','the blind navigator of the Ganga',
 '{"facts":["Declared India''s National Aquatic Animal in 2009","Almost blind, it navigates and hunts entirely by echolocation","Often swims on its side, trailing a flipper along the riverbed"],"habitat":"deep pools of the Ganga and Brahmaputra systems","size":"2–2.6 m long, 70–90 kg","superpower":"finding the way without needing to see","india_note":"a nationwide survey published in 2025 estimated roughly 6,300 river dolphins in India"}',
 false, 90),
('king-cobra','KCB','King Cobra','national','default','rare','the king of the rainforest',
 '{"facts":["The longest venomous snake in the world, reaching 5.5 m","The only snake that builds a nest of leaves for its eggs and guards it","Eats mostly other snakes"],"habitat":"rainforest and wet evergreen forest","size":"3–4 m typical, up to 5.5 m","superpower":"calm authority over every other snake","india_note":"Agumbe in Karnataka hosts a research station devoted to it; in 2024 the Western Ghats population was named a separate species, Ophiophagus kaalinga"}',
 false, 91),

-- ===== secret =====
('himalayan-monal','MNL','Himalayan Monal','secret','default','epic','the fully connected one',
 '{"facts":["Males shimmer in nine iridescent colours","Digs through snow with a strong curved bill for roots and tubers","National bird of Nepal, where it is called the danphe"],"habitat":"oak and conifer forest and alpine meadows at 2,400–4,500 m","size":"about 70 cm long, 2–2.4 kg","superpower":"every colour, all at once","india_note":"state bird of Uttarakhand; seen above Chopta and in the Great Himalayan National Park"}',
 true, 99),

-- ===== regional (one per region code) =====
('rose-ringed-parakeet','PRK','Rose-ringed Parakeet','regional','default','rare','the chatter of Andhra skies',
 '{"facts":["Only the males wear the rose and black neck ring","Can mimic human speech and whistles","Nests in tree hollows and crevices in buildings, and has founded feral colonies in London and Amsterdam"],"habitat":"farmland, orchards and city parks","size":"about 40 cm including the tail, 115–140 g","superpower":"colour and chatter wherever it goes","india_note":"state bird of Andhra Pradesh"}',
 false, 101),
('mithun','MTH','Mithun','regional','default','rare','the pride of the hills',
 '{"facts":["A semi-domesticated bovine descended from the gaur","Roams free in the forest and returns to its owners for salt","Given as bride price and counted as wealth in the hill communities of the northeast"],"habitat":"hill forests of the eastern Himalaya","size":"around 1.5 m at the shoulder, 400–650 kg","superpower":"strength the whole village counts on","india_note":"state animal of Arunachal Pradesh and Nagaland"}',
 false, 102),
('one-horned-rhino','RHN','One-horned Rhino','regional','default','epic','the armoured giant of Kaziranga',
 '{"facts":["Deep skin folds make it look clad in riveted armour plates","Kaziranga held about 2,600 rhinos in the 2022 count, over two-thirds of the world population","A strong swimmer that wallows in rivers and feeds on aquatic plants"],"habitat":"tall grassland and riverine floodplain","size":"1.75–2 m at the shoulder, 1,800–2,700 kg","superpower":"an unshakeable presence","india_note":"state animal of Assam; also in Orang, Pobitora and Manas"}',
 false, 103),
('gaur','GAR','Gaur','regional','default','rare','the mountain of muscle',
 '{"facts":["The largest wild cattle on Earth; bulls can exceed 1,000 kg","A high dorsal ridge and white stockings make it unmistakable","Only tigers hunt adult gaur"],"habitat":"hill forest with grassy clearings","size":"1.8–2.2 m at the shoulder, 650–1,500 kg","superpower":"quiet power that moves mountains","india_note":"state animal of Bihar and Goa; found in Valmiki Tiger Reserve"}',
 false, 104),
('wild-water-buffalo','WBF','Wild Water Buffalo','regional','default','rare','the wide-horned sentinel',
 '{"facts":["Its horns span wider than any other living bovid, up to about 2 m tip to tip","The wild ancestor of every domestic water buffalo","Endangered, with only a few thousand left in the wild"],"habitat":"swampy grassland and river floodplains","size":"1.5–1.9 m at the shoulder, 700–1,200 kg","superpower":"guarding the wetlands with steady calm","india_note":"state animal of Chhattisgarh; found in Udanti-Sitanadi and Indravati"}',
 false, 105),
('olive-ridley-turtle','ORT','Olive Ridley Turtle','regional','default','rare','the one who always comes home',
 '{"facts":["Nests in arribadas, mass gatherings where hundreds of thousands of females come ashore together","The smallest sea turtle, around 60–70 cm long","Females return to the beach where they themselves hatched"],"habitat":"warm coastal seas and sandy beaches","size":"60–70 cm shell, 35–50 kg","superpower":"finding home across an ocean","india_note":"nests on Goa''s Morjim, Galgibaga and Agonda beaches; Odisha''s Rushikulya and Gahirmatha host the great arribadas"}',
 false, 106),
('asiatic-lion','LION','Asiatic Lion','regional','default','epic','the last lion of Asia',
 '{"facts":["The only wild lions outside Africa live in and around Gir, Gujarat","Counted at 674 in 2020 and 891 in the 2025 census","A long fold of skin along the belly and a sparser mane set it apart from African lions"],"habitat":"dry deciduous forest and scrub","size":"about 1.1 m at the shoulder, 110–190 kg","superpower":"the roar that came back from the brink","india_note":"state animal of Gujarat"}',
 false, 107),
('black-francolin','BFR','Black Francolin','regional','default','rare','the voice of the wheat fields',
 '{"facts":["Males are jet black with a chestnut collar and white cheek patch","Its loud, rasping call carries across wheat and sugarcane fields at dawn","Prefers to run through tall grass rather than fly"],"habitat":"tall grass, sugarcane and riverine scrub","size":"33–36 cm long","superpower":"a call that owns the morning fields","india_note":"state bird of Haryana"}',
 false, 108),
('western-tragopan','WTG','Western Tragopan','regional','default','rare','the jewel of Himachal',
 '{"facts":["One of the rarest pheasants in the world, with fewer than 5,000 thought to survive","Displaying males inflate a brilliant blue throat lappet and raise fleshy horns","First bred in captivity at the Sarahan pheasantry in Himachal Pradesh"],"habitat":"dense temperate forest at 2,400–3,600 m","size":"55–60 cm long, 1.8–2.2 kg","superpower":"beauty hidden deep in the forest","india_note":"state bird of Himachal Pradesh; Great Himalayan National Park is a stronghold"}',
 false, 109),
('indian-giant-flying-squirrel','FSQ','Indian Giant Flying Squirrel','regional','default','rare','the glider of the sal forest',
 '{"facts":["Glides between trees on a furred membrane stretched between its limbs","Single glides can cover more than 100 m","Strictly nocturnal, feeding on leaves, bark and fruit"],"habitat":"tall deciduous and evergreen forest","size":"30–45 cm body, tail 35–60 cm, 1–2 kg","superpower":"turning a leap into a flight","india_note":"found in the sal forests of Jharkhand, including Dalma and Palamau"}',
 false, 110),
('lion-tailed-macaque','LTM','Lion-tailed Macaque','regional','default','rare','the silver-maned sage',
 '{"facts":["A silver-grey mane frames its black face, and a tufted tail gives it its name","Found only in the Western Ghats","Among the most arboreal of all macaques, rarely coming to the ground"],"habitat":"wet evergreen forest canopy","size":"40–60 cm body, 2–10 kg","superpower":"wisdom of the high canopy","india_note":"lives in Karnataka''s Sharavathi and Aghanashini valleys and Kerala''s Silent Valley"}',
 false, 111),
('great-hornbill','HBL','Great Hornbill','regional','default','rare','the great one of the canopy',
 '{"facts":["The female seals herself inside a tree hollow with mud and droppings, leaving a slit through which the male feeds her for months","The huge casque on its bill is mostly hollow","Its wingbeats can be heard far across the forest"],"habitat":"tall evergreen forest with fruiting figs","size":"95–130 cm long, 2–4 kg, wingspan 1.5 m","superpower":"devotion that feeds a family through a slit in a tree","india_note":"state bird of Kerala and Arunachal Pradesh"}',
 false, 112),
('barasingha','BSG','Barasingha','regional','default','rare','the twelve-tined survivor',
 '{"facts":["The name means twelve-tined, for the stag''s many-pointed antlers","Kanha''s hard-ground barasingha recovered from just 66 animals in 1970 to more than 800","Splayed hooves help it walk on marshy ground"],"habitat":"swampy grassland and open sal forest","size":"1.1–1.2 m at the shoulder, 170–280 kg","superpower":"the comeback of a lifetime","india_note":"state animal of Madhya Pradesh; Kanha National Park is its home"}',
 false, 113),
('indian-giant-squirrel','GSQ','Indian Giant Squirrel','regional','default','rare','the painted leaper',
 '{"facts":["Leaps up to 6 m between trees","Its coat mixes maroon, cream and black like a painting","Builds several globe-shaped nests and moves between them"],"habitat":"tall deciduous and evergreen forest","size":"about 36 cm body, tail up to 60 cm, 1.5–2 kg","superpower":"colour in motion through the treetops","india_note":"state animal of Maharashtra, the shekru; famous at Bhimashankar"}',
 false, 114),
('sangai','SNG','Sangai','regional','default','rare','the dancing deer of Loktak',
 '{"facts":["Lives only on floating mats of vegetation called phumdi on Loktak Lake","Called the dancing deer for its careful, bouncing gait on the floating ground","Down to just 14 animals in 1975, it recovered to around 260 by 2016"],"habitat":"floating marshland of Keibul Lamjao, the world''s only floating national park","size":"1.15–1.25 m at the shoulder, 95–125 kg","superpower":"dancing where the ground itself floats","india_note":"state animal of Manipur"}',
 false, 115),
('clouded-leopard','CLD','Clouded Leopard','regional','default','epic','the ghost of the mist',
 '{"facts":["Has the longest canine teeth relative to skull size of any living cat","Can climb down tree trunks head first and hang from branches by its hind feet","Cloud-shaped blotches give it its name"],"habitat":"dense evergreen hill forest","size":"60–110 cm body, 11–23 kg","superpower":"moving through the treetops like mist","india_note":"state animal of Meghalaya; Nokrek and Balpakram are strongholds"}',
 false, 116),
('himalayan-serow','SRW','Himalayan Serow','regional','default','rare','the cliff walker',
 '{"facts":["A goat-antelope with large scent glands in front of the eyes","Both sexes carry short, sharp horns","First recorded in the cold desert of Spiti in 2020"],"habitat":"steep forested slopes at 1,500–3,500 m","size":"about 1 m at the shoulder, 85–140 kg","superpower":"sure footing where no path exists","india_note":"state animal of Mizoram"}',
 false, 117),
('blyths-tragopan','BTG','Blyth''s Tragopan','regional','default','rare','the hidden prince of Nagaland',
 '{"facts":["Males show bare yellow facial skin and a red-orange neck","Listed as Vulnerable, surviving in remote mountain forests","Khonoma village in Nagaland banned hunting in 1998 to protect it"],"habitat":"evergreen oak and rhododendron forest at 1,800–3,300 m","size":"65–70 cm long, 1.5–2 kg","superpower":"royalty in the deepest forest","india_note":"state bird of Nagaland; found in Dzükou valley and the Saramati range"}',
 false, 118),
('irrawaddy-dolphin','IRD','Irrawaddy Dolphin','regional','default','rare','the smiling spirit of Chilika',
 '{"facts":["A rounded head with no beak gives it a gentle smiling look","Spits jets of water to herd fish","Lives happily in fresh, brackish and coastal water"],"habitat":"lagoons, estuaries and large rivers","size":"2–2.75 m long, 90–200 kg","superpower":"calm joy in every wave","india_note":"Chilika Lake in Odisha holds the largest lagoon population in the world, around 150 dolphins"}',
 false, 119),
('northern-goshawk','GHK','Northern Goshawk','regional','default','rare','the baaz of Punjab',
 '{"facts":["Short broad wings and a long tail let it twist through forest at speed","Adults have piercing red eyes","Females are much larger than males"],"habitat":"Himalayan forest; winters in the northern plains","size":"46–69 cm long, wingspan 89–127 cm","superpower":"focus and speed in tight spaces","india_note":"state bird of Punjab, the baaz associated with Guru Gobind Singh"}',
 false, 120),
('camel','CML','Camel','regional','default','rare','the ship of the desert',
 '{"facts":["The hump stores fat, not water","Can drink more than 100 litres in about ten minutes","Double rows of eyelashes and closable nostrils keep out blowing sand"],"habitat":"desert and arid scrub","size":"1.8–2 m at the shoulder, 400–600 kg","superpower":"endurance the desert cannot defeat","india_note":"state animal of Rajasthan since 2014; herded by the Raika people"}',
 false, 121),
('blood-pheasant','BPH','Blood Pheasant','regional','default','rare','the snowline wanderer',
 '{"facts":["Crimson streaks on the breast look like splashes of blood","Lives near the treeline at 3,200–4,700 m and follows the snowline up and down the year","Feeds on moss, lichen and fern shoots"],"habitat":"high rhododendron and fir forest near the snowline","size":"44–48 cm long","superpower":"thriving where the snow begins","india_note":"state bird of Sikkim"}',
 false, 122),
('nilgiri-tahr','TAHR','Nilgiri Tahr','regional','default','rare','the cliff-top champion',
 '{"facts":["Found only in the Western Ghats","Adult males develop a silvery saddle patch on the back","Eravikulam National Park shelters the largest herd, more than 700 animals"],"habitat":"grassy cliffs and shola above 1,200 m","size":"100–110 cm at the shoulder, 50–100 kg","superpower":"standing tall at the edge of the world","india_note":"state animal of Tamil Nadu"}',
 false, 123),
('striped-hyena','HYN','Striped Hyena','regional','default','rare','the night patrol',
 '{"facts":["Raises a long erectile mane to look much bigger when threatened","Jaws strong enough to crush bone","Mostly solitary and nocturnal, cleaning the landscape as a scavenger"],"habitat":"dry scrub, rocky hills and ravines","size":"60–80 cm at the shoulder, 25–55 kg","superpower":"keeping the night in order","india_note":"roams the Deccan drylands of Telangana"}',
 false, 124),
('phayres-langur','PHL','Phayre''s Langur','regional','default','rare','the spectacled sage',
 '{"facts":["White rings around the eyes earn it the name spectacled langur","Infants are born bright orange","A multi-chambered stomach digests tough leaves"],"habitat":"evergreen and bamboo forest","size":"50–60 cm body, tail 65–85 cm, 6–8 kg","superpower":"seeing clearly through the canopy","india_note":"state animal of Tripura; Sepahijala Wildlife Sanctuary is a stronghold"}',
 false, 125),
('sarus-crane','SRS','Sarus Crane','regional','default','rare','the tallest dancer',
 '{"facts":["The tallest flying bird in the world, up to 1.8 m","Pairs mate for life and dance together with trumpeting duets","Nests in wetlands and paddy fields alongside farmers"],"habitat":"wetlands, marshes and flooded fields","size":"1.5–1.8 m tall, 6–12 kg, wingspan 2.2–2.5 m","superpower":"loyalty that stands taller than anyone","india_note":"state bird of Uttar Pradesh, which holds the largest population, over 19,000 in the 2023 state count"}',
 false, 126),
('musk-deer','MSK','Musk Deer','regional','default','rare','the fanged phantom of the high forests',
 '{"facts":["Has no antlers; males grow long sabre-like canine teeth instead","Males carry a musk gland that has made them a target for poachers","Solitary and shy, living at 2,500–4,500 m"],"habitat":"alpine scrub and high conifer forest","size":"50–60 cm at the shoulder, 11–18 kg","superpower":"vanishing into the high forest","india_note":"state animal of Uttarakhand; Kedarnath Musk Deer Sanctuary is named for it"}',
 false, 127),
('fishing-cat','FCT','Fishing Cat','regional','default','rare','the swimmer of the Sundarbans',
 '{"facts":["Partially webbed feet and a double layer of fur suit it to swimming","Dives after fish, twice the size of a house cat at 8–14 kg","Listed as Vulnerable as wetlands shrink"],"habitat":"mangroves, marshes and reed beds","size":"57–78 cm body, 8–14 kg","superpower":"a cat that loves the water","india_note":"state animal of West Bengal, the baghrol; found in the Sundarbans and Howrah wetlands"}',
 false, 128),
('dugong','DGG','Dugong','regional','default','epic','the gentle sea gardener',
 '{"facts":["The only herbivorous marine mammal in Indian waters, grazing seagrass meadows","More closely related to elephants than to whales","India''s first dugong conservation reserve was notified in Palk Bay, Tamil Nadu in 2022"],"habitat":"shallow seagrass beds","size":"2.4–3 m long, 250–400 kg","superpower":"tending the meadows of the sea","india_note":"state animal of the Andaman and Nicobar Islands; only a couple of hundred remain in Indian seas"}',
 false, 129),
('grey-mongoose','MNG','Grey Mongoose','regional','default','rare','the cobra''s rival',
 '{"facts":["The real-life Rikki-Tikki-Tavi","Takes on cobras with speed, a thick coat and receptors that resist the venom","Active by day, hunting rodents, snakes and insects"],"habitat":"scrub, farmland, gardens and city parks","size":"36–45 cm body, 0.9–1.7 kg","superpower":"quickness that outwits danger","india_note":"state animal of Chandigarh"}',
 false, 130),
('hoopoe','HOP','Hoopoe','regional','default','rare','the crowned wanderer',
 '{"facts":["Raises its crest into a fan when alarmed or landing","Probes soil with a long curved bill for grubs","Its name echoes its soft oop-oop-oop call"],"habitat":"lawns, orchards, open woodland and coasts","size":"25–32 cm long, wingspan 44–48 cm","superpower":"a crown worn lightly","india_note":"a familiar sight on lawns and shorelines of Daman, Diu and Dadra and Nagar Haveli"}',
 false, 131),
('house-sparrow','SPR','House Sparrow','regional','default','rare','the city''s oldest neighbour',
 '{"facts":["World Sparrow Day is held on 20 March each year","Nests in walls, lamp posts and air-conditioner vents","City numbers fell as nesting niches and insect food for chicks disappeared"],"habitat":"towns, villages and farmland","size":"14–16 cm long, 24–40 g","superpower":"living alongside us for thousands of years","india_note":"state bird of Delhi since 2012"}',
 false, 132),
('hangul','HNG','Hangul','regional','default','rare','the crown of Kashmir',
 '{"facts":["The only red deer in India","Stags carry antlers of up to five points a side","Critically Endangered, with around 290 counted in the 2023 census"],"habitat":"temperate forest and alpine meadows","size":"1.2–1.4 m at the shoulder, 150–250 kg","superpower":"a crown held high against the odds","india_note":"state animal of Jammu and Kashmir; almost all live in Dachigam National Park"}',
 false, 133),
('black-necked-crane','BNC','Black-necked Crane','regional','default','rare','the dancer of the high plateau',
 '{"facts":["The only crane that lives on high plateaus, breeding at 2,900–4,900 m","Pairs mate for life and perform leaping dances","Sacred to Buddhist communities of the Himalaya"],"habitat":"high-altitude marshes and lake shores","size":"1.15–1.4 m tall, 5–5.5 kg, wingspan 2–2.3 m","superpower":"grace above the clouds","india_note":"state bird of Ladakh; breeds at Tso Kar and Hanle in Changthang"}',
 false, 134),
('butterfly-fish','BFF','Butterfly Fish','regional','default','rare','the reef''s living jewel',
 '{"facts":["More than 120 species live on coral reefs worldwide","Many carry a false eyespot near the tail to confuse predators","Thin, disc-shaped bodies slip into coral crevices at night"],"habitat":"shallow coral reefs","size":"12–22 cm long","superpower":"colour that keeps the reef alive","india_note":"state animal of Lakshadweep; its presence signals a healthy reef"}',
 false, 135),
('palm-squirrel','PSQ','Palm Squirrel','regional','default','rare','the striped helper',
 '{"facts":["Legend says Lord Rama stroked the squirrel in thanks for helping build the bridge to Lanka, leaving three stripes","Active by day, with a shrill chirping alarm call","Builds grass nests in trees and on rooftops"],"habitat":"gardens, groves, towns and palm trees","size":"15–20 cm body, tail about as long, 100–120 g","superpower":"small hands, big help","india_note":"state animal of Puducherry; the three-striped squirrel of southern India"}',
 false, 136)
)
insert into animals(slug, code, name, family, rarity, flavour_line, encyclopedia, art, palette, is_secret, sort_order)
select a.slug, a.code, a.name, a.family, a.rarity::rarity_t, a.flavour_line, a.encyclopedia::jsonb,
       jsonb_build_object('baby',  'card-art/' || a.slug || '/baby.png',
                          'young', 'card-art/' || a.slug || '/young.png',
                          'adult', 'card-art/' || a.slug || '/adult.png'),
       pal.palette, a.is_secret, a.sort_order
from a
join pal on pal.family = a.family and pal.bag = a.bag
on conflict (slug) do update set
  code         = excluded.code,
  name         = excluded.name,
  family       = excluded.family,
  rarity       = excluded.rarity,
  flavour_line = excluded.flavour_line,
  encyclopedia = excluded.encyclopedia,
  art          = excluded.art,
  palette      = excluded.palette,
  is_secret    = excluded.is_secret,
  sort_order   = excluded.sort_order,
  is_active    = true;

-- ---------- rules ----------
delete from animal_rules where note like 'seed:%';

insert into animal_rules(animal_id, scope, tier, predicates, weight, first_time_guaranteed, repeat_probability, note)
select an.id, r.scope::card_scope_t, r.tier, r.predicates::jsonb, r.weight, r.ftg, r.rp, 'seed:' || r.slug
from (values
-- tier 0 · speed bands (always available; no guarantee semantics)
('chinkara',            'run', 0, '{"speed_bands":["swift"]}',  1.0, false, 1.0),
('horse',               'run', 0, '{"speed_bands":["swift"]}',  1.0, false, 1.0),
('blackbuck',           'run', 0, '{"speed_bands":["swift"]}',  1.0, false, 1.0),
('indian-hare',         'run', 0, '{"speed_bands":["swift"]}',  1.0, false, 1.0),
('peregrine-falcon',    'run', 0, '{"speed_bands":["swift"]}',  1.0, false, 1.0),
('cheetah',             'run', 0, '{"speed_bands":["swift"]}',  1.0, false, 1.0),
('chital',              'run', 0, '{"speed_bands":["steady"]}', 1.0, false, 1.0),
('desi-dog',            'run', 0, '{"speed_bands":["steady"]}', 1.0, false, 1.0),
('nilgai',              'run', 0, '{"speed_bands":["steady"]}', 1.0, false, 1.0),
('dhole',               'run', 0, '{"speed_bands":["steady"]}', 1.0, false, 1.0),
('indian-wolf',         'run', 0, '{"speed_bands":["steady"]}', 1.0, false, 1.0),
('leopard',             'run', 0, '{"speed_bands":["steady"]}', 1.0, false, 1.0),
('rabbit',              'run', 0, '{"speed_bands":["calm"]}',   1.0, false, 1.0),
('cat',                 'run', 0, '{"speed_bands":["calm"]}',   1.0, false, 1.0),
('grey-langur',         'run', 0, '{"speed_bands":["calm"]}',   1.0, false, 1.0),
('peacock',             'run', 0, '{"speed_bands":["calm"]}',   1.0, false, 1.0),
('smooth-coated-otter', 'run', 0, '{"speed_bands":["calm"]}',   1.0, false, 1.0),
('mouse-deer',          'run', 0, '{"speed_bands":["calm"]}',   1.0, false, 1.0),
('star-tortoise',       'run', 0, '{"speed_bands":["gentle"]}', 1.0, false, 1.0),
('hamster',             'run', 0, '{"speed_bands":["gentle"]}', 1.0, false, 1.0),
('sloth-bear',          'run', 0, '{"speed_bands":["gentle"]}', 1.0, false, 1.0),
('porcupine',           'run', 0, '{"speed_bands":["gentle"]}', 1.0, false, 1.0),
('pangolin',            'run', 0, '{"speed_bands":["gentle"]}', 1.0, false, 1.0),
('elephant',            'run', 0, '{"speed_bands":["gentle","calm"],"min_km":8}', 1.0, false, 1.0),

-- tier 1 · time of day
('indian-eagle-owl',    'run', 1, '{"time_windows":["night"]}', 1.0, true, 0.35),
('nightjar',            'run', 1, '{"time_windows":["night"]}', 1.0, true, 0.35),
('fruit-bat',           'run', 1, '{"time_windows":["night"]}', 1.0, true, 0.35),
('palm-civet',          'run', 1, '{"time_windows":["night"]}', 1.0, true, 0.35),
('rooster',             'run', 1, '{"time_windows":["dawn"]}',  1.0, true, 0.35),
('bulbul',              'run', 1, '{"time_windows":["dawn"]}',  1.0, true, 0.35),
('koel',                'run', 1, '{"time_windows":["dawn"]}',  1.0, true, 0.35),
('indian-roller',       'run', 1, '{"time_windows":["dawn"]}',  1.0, true, 0.35),

-- tier 2 · explorer
('indian-fox',          'run', 2, '{"requires_flags":["explorer"]}', 1.0, true, 0.5),
('bengal-monitor',      'run', 2, '{"requires_flags":["explorer"]}', 1.0, true, 0.5),
('golden-jackal',       'run', 2, '{"requires_flags":["explorer"]}', 1.0, true, 0.5),
('honey-badger',        'run', 2, '{"requires_flags":["explorer"]}', 1.0, true, 0.5),

-- tier 3 · new-state souvenir (run) + monthly regional pool
('rose-ringed-parakeet',          'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-AP"]}', 1.0, true,  0.2),
('rose-ringed-parakeet',          'monthly', 0, '{"region_codes":["IN-AP"]}', 1.0, false, 1.0),
('mithun',                        'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-AR"]}', 1.0, true,  0.2),
('mithun',                        'monthly', 0, '{"region_codes":["IN-AR"]}', 1.0, false, 1.0),
('one-horned-rhino',              'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-AS"]}', 1.0, true,  0.2),
('one-horned-rhino',              'monthly', 0, '{"region_codes":["IN-AS"]}', 1.0, false, 1.0),
('gaur',                          'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-BR"]}', 1.0, true,  0.2),
('gaur',                          'monthly', 0, '{"region_codes":["IN-BR"]}', 1.0, false, 1.0),
('wild-water-buffalo',            'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-CT"]}', 1.0, true,  0.2),
('wild-water-buffalo',            'monthly', 0, '{"region_codes":["IN-CT"]}', 1.0, false, 1.0),
('olive-ridley-turtle',           'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-GA"]}', 1.0, true,  0.2),
('olive-ridley-turtle',           'monthly', 0, '{"region_codes":["IN-GA"]}', 1.0, false, 1.0),
('asiatic-lion',                  'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-GJ"]}', 1.0, true,  0.2),
('asiatic-lion',                  'monthly', 0, '{"region_codes":["IN-GJ"]}', 1.0, false, 1.0),
('black-francolin',               'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-HR"]}', 1.0, true,  0.2),
('black-francolin',               'monthly', 0, '{"region_codes":["IN-HR"]}', 1.0, false, 1.0),
('western-tragopan',              'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-HP"]}', 1.0, true,  0.2),
('western-tragopan',              'monthly', 0, '{"region_codes":["IN-HP"]}', 1.0, false, 1.0),
('indian-giant-flying-squirrel',  'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-JH"]}', 1.0, true,  0.2),
('indian-giant-flying-squirrel',  'monthly', 0, '{"region_codes":["IN-JH"]}', 1.0, false, 1.0),
('lion-tailed-macaque',           'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-KA"]}', 1.0, true,  0.2),
('lion-tailed-macaque',           'monthly', 0, '{"region_codes":["IN-KA"]}', 1.0, false, 1.0),
('great-hornbill',                'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-KL"]}', 1.0, true,  0.2),
('great-hornbill',                'monthly', 0, '{"region_codes":["IN-KL"]}', 1.0, false, 1.0),
('barasingha',                    'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-MP"]}', 1.0, true,  0.2),
('barasingha',                    'monthly', 0, '{"region_codes":["IN-MP"]}', 1.0, false, 1.0),
('indian-giant-squirrel',         'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-MH"]}', 1.0, true,  0.2),
('indian-giant-squirrel',         'monthly', 0, '{"region_codes":["IN-MH"]}', 1.0, false, 1.0),
('sangai',                        'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-MN"]}', 1.0, true,  0.2),
('sangai',                        'monthly', 0, '{"region_codes":["IN-MN"]}', 1.0, false, 1.0),
('clouded-leopard',               'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-ML"]}', 1.0, true,  0.2),
('clouded-leopard',               'monthly', 0, '{"region_codes":["IN-ML"]}', 1.0, false, 1.0),
('himalayan-serow',               'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-MZ"]}', 1.0, true,  0.2),
('himalayan-serow',               'monthly', 0, '{"region_codes":["IN-MZ"]}', 1.0, false, 1.0),
('blyths-tragopan',               'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-NL"]}', 1.0, true,  0.2),
('blyths-tragopan',               'monthly', 0, '{"region_codes":["IN-NL"]}', 1.0, false, 1.0),
('irrawaddy-dolphin',             'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-OR"]}', 1.0, true,  0.2),
('irrawaddy-dolphin',             'monthly', 0, '{"region_codes":["IN-OR"]}', 1.0, false, 1.0),
('northern-goshawk',              'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-PB"]}', 1.0, true,  0.2),
('northern-goshawk',              'monthly', 0, '{"region_codes":["IN-PB"]}', 1.0, false, 1.0),
('camel',                         'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-RJ"]}', 1.0, true,  0.2),
('camel',                         'monthly', 0, '{"region_codes":["IN-RJ"]}', 1.0, false, 1.0),
('blood-pheasant',                'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-SK"]}', 1.0, true,  0.2),
('blood-pheasant',                'monthly', 0, '{"region_codes":["IN-SK"]}', 1.0, false, 1.0),
('nilgiri-tahr',                  'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-TN"]}', 1.0, true,  0.2),
('nilgiri-tahr',                  'monthly', 0, '{"region_codes":["IN-TN"]}', 1.0, false, 1.0),
('striped-hyena',                 'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-TG"]}', 1.0, true,  0.2),
('striped-hyena',                 'monthly', 0, '{"region_codes":["IN-TG"]}', 1.0, false, 1.0),
('phayres-langur',                'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-TR"]}', 1.0, true,  0.2),
('phayres-langur',                'monthly', 0, '{"region_codes":["IN-TR"]}', 1.0, false, 1.0),
('sarus-crane',                   'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-UP"]}', 1.0, true,  0.2),
('sarus-crane',                   'monthly', 0, '{"region_codes":["IN-UP"]}', 1.0, false, 1.0),
('musk-deer',                     'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-UT"]}', 1.0, true,  0.2),
('musk-deer',                     'monthly', 0, '{"region_codes":["IN-UT"]}', 1.0, false, 1.0),
('fishing-cat',                   'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-WB"]}', 1.0, true,  0.2),
('fishing-cat',                   'monthly', 0, '{"region_codes":["IN-WB"]}', 1.0, false, 1.0),
('dugong',                        'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-AN"]}', 1.0, true,  0.2),
('dugong',                        'monthly', 0, '{"region_codes":["IN-AN"]}', 1.0, false, 1.0),
('grey-mongoose',                 'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-CH"]}', 1.0, true,  0.2),
('grey-mongoose',                 'monthly', 0, '{"region_codes":["IN-CH"]}', 1.0, false, 1.0),
('hoopoe',                        'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-DH"]}', 1.0, true,  0.2),
('hoopoe',                        'monthly', 0, '{"region_codes":["IN-DH"]}', 1.0, false, 1.0),
('house-sparrow',                 'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-DL"]}', 1.0, true,  0.2),
('house-sparrow',                 'monthly', 0, '{"region_codes":["IN-DL"]}', 1.0, false, 1.0),
('hangul',                        'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-JK"]}', 1.0, true,  0.2),
('hangul',                        'monthly', 0, '{"region_codes":["IN-JK"]}', 1.0, false, 1.0),
('black-necked-crane',            'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-LA"]}', 1.0, true,  0.2),
('black-necked-crane',            'monthly', 0, '{"region_codes":["IN-LA"]}', 1.0, false, 1.0),
('butterfly-fish',                'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-LD"]}', 1.0, true,  0.2),
('butterfly-fish',                'monthly', 0, '{"region_codes":["IN-LD"]}', 1.0, false, 1.0),
('palm-squirrel',                 'run',     3, '{"requires_flags":["new_state"],"region_codes":["IN-PY"]}', 1.0, true,  0.2),
('palm-squirrel',                 'monthly', 0, '{"region_codes":["IN-PY"]}', 1.0, false, 1.0),

-- national · monthly fallback (matches every state, so weighted down)
('ganges-river-dolphin', 'monthly', 0, '{}', 0.3, false, 1.0),
('king-cobra',           'monthly', 0, '{}', 0.3, false, 1.0),

-- weekly · tier = run-days the bag needs
('red-panda',            'weekly', 3, '{"min_run_days":3}', 1.0, false, 1.0),
('sambar',               'weekly', 3, '{"min_run_days":3}', 1.0, false, 1.0),
('gharial',              'weekly', 3, '{"min_run_days":3}', 1.0, false, 1.0),
('snow-leopard',         'weekly', 5, '{"min_run_days":5}', 1.0, false, 1.0),
('black-panther',        'weekly', 5, '{"min_run_days":5}', 1.0, false, 1.0),
('markhor',              'weekly', 5, '{"min_run_days":5}', 1.0, false, 1.0),
('bengal-tiger',         'weekly', 7, '{"min_run_days":7}', 1.0, false, 1.0),
('great-indian-bustard', 'weekly', 7, '{"min_run_days":7}', 1.0, false, 1.0),

-- tier 4 · migratory
('bar-headed-goose',     'run', 4, '{"requires_flags":["migratory_2"]}', 1.0, true, 0.5),
('greater-flamingo',     'run', 4, '{"requires_flags":["migratory_2"]}', 1.0, true, 0.5),
('amur-falcon',          'run', 4, '{"requires_flags":["migratory_3"]}', 1.0, true, 0.5),
('demoiselle-crane',     'run', 4, '{"requires_flags":["migratory_3"]}', 1.0, true, 0.5),

-- secret · every data purpose granted
('himalayan-monal',      'run', 0, '{"requires_connected":["location","motion","steps","heart_rate"]}', 0.5, false, 1.0)
) as r(slug, scope, tier, predicates, weight, ftg, rp)
join animals an on an.slug = r.slug;

-- ---------- sanity ----------
do $$ begin
  assert (select count(*) from animals) >= 80, 'animal seed incomplete';
  assert (select count(*) from animal_rules where note like 'seed:%') >= 100, 'rule seed incomplete';
  assert not exists (select 1 from animals a where not exists (select 1 from animal_rules r where r.animal_id = a.id)),
    'every animal needs at least one rule';
  assert not exists (select 1 from regions g where g.kind in ('state','ut')
                     and not exists (select 1 from animal_rules r where r.scope = 'monthly' and r.predicates->'region_codes' ? g.code)),
    'every state/UT needs a regional animal';
end $$;
